const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");
const webScraping = require("./web-scraping");
const processImageGeneration = require("./process-image");
const chatGPT = require("../services/gpt-completions");
const uploadCloudinary = require("../services/cloudinary");
const slugify = require("../utils/slugify");
const prompts = require("./prompts");
const debugMe = require("../utils/debug-me");

/**
 * Generates and saves the blog post content using AI, based on the provided frontmatter.
 *
 * @param {object} frontmatter - The frontmatter data, whether from a draft or direct input.
 * @param {object} aiSettings - AI configuration settings.
 * @param {object} authorsData - Data related to post authors.
 * @param {object} i18n - Internationalization settings.
 * @param {boolean} autoPost - Indicates if the post is being processed automatically without a specific draft.
 * @param {boolean} debug - Enables debug mode for logging additional information.
 */
async function generatePostContent(
  contentFolderPath,
  frontmatter,
  aiSettings,
  authorsData,
  i18n,
  gptKey,
  folderName,
  cloudName,
  cloudApiKey,
  cloudinarySecret,
  autoPost,
  debug
) {
  debugMe(debug, "Generate Content", {
    contentFolderPath,
    // aiSettings,
    // frontmatter,
    // authorsData,
    i18n,
    autoPost,
    debug,
  });

  try {
    // Step 2: Use AI to generate content and images based on the frontmatter
    const aiGeneratedContent = await scrapeToAiPipeline(
      frontmatter,
      aiSettings,
      authorsData,
      i18n,
      gptKey,
      folderName,
      cloudName,
      cloudApiKey,
      cloudinarySecret,
      autoPost,
      debug
    );
    const postImgsUrl = aiGeneratedContent.postImgsUrl;

    // Step 3: Parse the AI-generated content into a markdown format, incorporating images
    const postContent = MD.parse(
      postImgsUrl,
      frontmatter,
      aiGeneratedContent.aiResponse
    );

    // Step 4: Save the final post content to a file and optionally delete the draft
    savePostContent(
      postContent,
      aiGeneratedContent.aiResponse,
      frontmatter.draftFilePath,
      contentFolderPath,
      autoPost,
      debug
    );
  } catch (err) {
    console.error("Error generating post content:", err);
  }
}
/**
 * Saves the final post content to a file and optionally deletes the draft file.
 *
 * @param {string} postContent - The final formatted content of the post in markdown.
 * @param {object} aiResponse - The response content generated by the AI.
 * @param {string} draftFilePath - Path to the original draft file.
 * @param {boolean} autoPost - Indicates if the post is being processed automatically without a specific draft.
 */
function savePostContent(
  postContent,
  aiResponse,
  draftFilePath,
  contentFolder,
  autoPost,
  debug
) {
  debugMe(debug, "Save Post", {
    postContent,
    aiResponse,
    draftFilePath,
    contentFolder,
    autoPost,
  });

  const postFilePath = path.join(contentFolder, "/posts");
  const postSlug = slugify(aiResponse?.title);
  const postFilename = `${postSlug || "fail-post"}.md`;

  try {
    fs.writeFileSync(`${postFilePath}/${postFilename}`, postContent, "utf8");

    // Delete the original draft file if it's not an auto post
    if (!autoPost && draftFilePath) {
      fs.unlinkSync(draftFilePath);
      console.log(`Draft deletado com sucesso: ${draftFilePath}`);
    }
    return console.log(
      `Post gerado com sucesso: ${postFilePath}/${postFilename}`
    );
  } catch (error) {
    return console.error("Erro ao gravar post:", error);
  }
}

/**
 * Pipeline to generate AI-based content and images.
 * It combines the draft's frontmatter with scraped data (if needed) and prompts AI tools to generate the post content.
 *
 * @param {object} draftFrontmatter - Object containing the frontmatter, content, and draft file path.
 * @param {boolean} autoPost - Indicates if the post is being processed automatically without a specific draft.
 * @param {boolean} debug - Enables debug mode for logging additional information.
 * @returns {object} An object containing the AI-generated content and the URLs of generated images.
 */
async function scrapeToAiPipeline(
  draftFrontmatter,
  aiSettings,
  authorsData,
  i18n,
  gptKey,
  folderName,
  cloudName,
  cloudApiKey,
  cloudinarySecret,
  autoPost,
  debug
) {
  const { aiUrlSource, mdTransformPrompt } = aiSettings.autoPostsSettings;
  const { gptModel, body, jsonResponse } = aiSettings;
  // gptModel, prompts, gptKey, debug
  debugMe(debug, "ChatGPT", {
    gptModel,
    gptKey,
    autoPost: autoPost,
    debug,
  });
  console.log(
    "aiUrlSourceaiUrlSourceaiUrllSourceaiUrlSourceaiUrlSourceaiUrlSourceaiUrlSourceaiUrlSource"
  );
  console.log(aiUrlSource);

  const frontmatter = draftFrontmatter?.frontmatter || null;
  const content = draftFrontmatter?.content || null;
  console.log("autoPost>>>>>>>>>>>", autoPost);

  let webScrape = null;
  if (autoPost) {
    console.log("22222222222222222222222222");
    // Get a random news source URL from AI settings for scraping
    const randomIndex =
      aiUrlSource?.length >= 2
        ? Math.floor(Math.random() * aiUrlSource?.length)
        : 0;
    const randomSourceUrl = aiUrlSource[randomIndex]?.href;
    webScrape = await webScraping([randomSourceUrl], autoPost, debug);
  } else {
    // debugMe(debug, "Links to Scraping", frontmatter?.linkAiDraft);
    console.log('frontmatter || "nada", autoPost, debug');
    console.log(frontmatter || "nada", autoPost, debug);

    webScrape = await webScraping(
      Object.values(frontmatter?.linkAiDraft),
      autoPost,
      debug
    );
  }

  debugMe(debug, "Web Scraping", webScrape);

  // Generate prompts for AI based on the frontmatter, content, and optionally the latest news
  const promptText = Object.values(
    await prompts(
      body,
      authorsData,
      content,
      mdTransformPrompt,
      jsonResponse,
      i18n,
      autoPost,
      webScrape
    )
  )
    .filter(Boolean)
    .join("\n\n");

  debugMe(debug, "Prompts to Send", promptText);

  // Send the prompts to ChatGPT and get the AI-generated response
  const aiResponse = await chatGPT(gptModel, promptText, gptKey, debug);
  debugMe(debug, "A.I. Response", aiResponse);

  // Generate images based on the prompts using DALL-E
  const gptImgsUrl = await processImageGeneration(
    frontmatter?.main_image_prompt || aiResponse?.title,
    frontmatter?.additional_image_prompts || [],
    gptKey,
    debug
  );

  debugMe(debug, "Dall-E Images", gptImgsUrl);

  // Upload the generated images to Cloudinary and get their URLs
  const postImgsUrl = await uploadCloudinary(
    gptImgsUrl,
    folderName,
    cloudName,
    cloudApiKey,
    cloudinarySecret
  );

  debugMe(debug, "Cloudinary Upload", postImgsUrl);

  return { aiResponse, postImgsUrl };
}

const MD = {
  /**
   * Parses the generated AI content and images into markdown format.
   * The content is structured with embedded images, and frontmatter is created for the post.
   *
   * @param {array} postImgsUrl - Array of URLs for the images generated by AI.
   * @param {object} draftFrontmatter - The original frontmatter extracted from the draft.
   * @param {object} aiResponse - The response content generated by the AI.
   * @returns {string} The formatted markdown content for the post.
   */
  parse: function (postImgsUrl, draftFrontmatter, aiResponse) {
    //organizePostContent
    const { frontmatter } = draftFrontmatter;

    const postFrontmatter = {
      title: aiResponse.title,
      author: aiResponse.author,
      categories:
        aiResponse.categories || frontmatter.categories || "Uncategorized",
      tags: aiResponse.tag || aiResponse.tags || frontmatter.tags || [],
      date: new Date().toISOString(),
      image: postImgsUrl[0]?.mainImg || "cover.jpg",
      draft: true,
      featuredPost: false,
      layout: "post",
    };

    let postBody = aiResponse?.body;
    let imageIndex = 0;

    const remainingImages = postImgsUrl?.slice(1) || [];

    // Embed images in the markdown content where headings are present
    postBody = postBody?.replace(/(##\s+.+)/g, (heading) => {
      if (imageIndex < remainingImages?.length) {
        const imageMarkdown = `![${aiResponse.title}](${remainingImages[imageIndex].headingsImgs})\n\n`;
        imageIndex++;
        return `${imageMarkdown}${heading}`;
      }
      return heading;
    });

    return `---\n${yaml.dump(postFrontmatter)}---\n\n${postBody}`;
  },
};

module.exports = generatePostContent;
