name: Trigger Update

on:
  repository_dispatch:
    types: [trigger-sync]
# on:
#   push:
#     branches:
#       - master
jobs:
  update-core-src:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Checkout repository
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.PAT }}
          node-version: "20.x"

      - name: Remove old core/src files
        run: rm -rf core/src

      - name: Clone nextjs-source repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git clone --depth 1 https://$GITHUB_TOKEN@github.com/schindyguy/nextjs-source.git temp-source
          mkdir core/src
          cp -R temp-source/* core/src/
          rm -rf temp-source

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Commit changes if there are any
        run: |
          git config --global user.name 'schindyguy'
          git config --global user.email 'bschindelheim@gmail.com'
          git status          
          git add core/src/
          git add content/cache/ content/public/ .github/workflows/*.yml
          git add core/public/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "✔️ [Auto Commit]: Staging before rebase"
          fi

      - name: Pull with rebase
        run: |
          git pull --rebase

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to push"
          else
            git push https://$GITHUB_TOKEN@github.com/schindyguy/bt-template.git HEAD:master
          fi
