name: Watch Pages and Posts

on:
  push:
    paths:
      - "content/posts/**"
      - "content/pages/**"
  workflow_dispatch:

permissions: write-all

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          # Fine-grained PAT with contents:write and workflows:write
          # scopes
          token: ${{ secrets.PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: "[🤰 DIGEST IT]: update('posts')"
        run: npm run update

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'schindyguy'
          git config --global user.email 'bschindelheim@gmail.com'
          git pull
          git add content/public/ content/cache/ .github/workflows/
          git status
          if git diff-index --quiet HEAD --; then
              echo "No changes to commit"
          else
              git commit -m "✔️ [🤰 DIGEST IT]: update('posts')"
          fi

      - name: Pull with rebase
        run: git pull --rebase

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push https://$GITHUB_TOKEN@github.com/schindyguy/mt.git HEAD:master
